// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { registerPolarisControllers } from "polaris-view-components"

import HelloController from "./hello_controller"
import FlashController from "./flash_controller"
import FormController from "./form_controller"
import FlatpickrController from "./flatpickr_controller"

registerPolarisControllers(Stimulus)
application.register("hello", HelloController)
application.register("flash", FlashController)
application.register("form", FormController)
application.register("flatpickr", FlatpickrController)
