name: 'New Pull Request Opened :rocket:'

on:
  pull_request:
    types:
      - opened

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: |
          A new pull request has been created by *${{ github.actor }}*!
          - *Title:* ${{ github.event.pull_request.title }}
          - *Link:* <${{ github.event.pull_request.html_url }}|View Pull Request>
